name: Build and Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Node.jsのセットアップ
        with:
          node-version: '22.13.1'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: List directory contents
        run: ls -la

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "dist directory does not exist"
            exit 1
          fi

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /manapuraza/
