name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Node.jsのセットアップ
        with:
          node-version: '18'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          # git-ftp-args: --remote-root /manapuraza
